"""
Mr.Creative Agent Pipeline
Orchestrates all agents to generate a full content batch.
"""

import json
import os
import time
import uuid
from datetime import datetime


def _check_job_control(job, db):
    """Check pause/stop flags. Returns True to continue, False to stop."""
    while True:
        db.session.refresh(job)
        if job.control_action == 'stop':
            job.status = 'complete'
            job.message = f'Stopped by user at {job.progress}%'
            job.completed_at = datetime.now()
            db.session.commit()
            return False
        if job.control_action == 'pause':
            job.message = 'Paused — waiting to resume...'
            db.session.commit()
            time.sleep(3)
            continue
        return True


def run_agent_pipeline(app, job_id):
    """Run the full agent pipeline for a job. Called in a background thread."""
    with app.app_context():
        from models import db, AgentJob, BrandKit, Collection, Generation
        from modules.agents import AgentEngine
        from modules.pollinations_api import PollinationsAPI

        job = AgentJob.query.get(job_id)
        if not job:
            print(f"[Pipeline] Job {job_id} not found!")
            return

        brand_kit = BrandKit.query.get(job.brand_kit_id)
        if not brand_kit:
            job.status = 'failed'
            job.error_message = 'Brand kit not found'
            db.session.commit()
            return

        groq_key = app.config.get('GROQ_API_KEY', '')
        if not groq_key:
            job.status = 'failed'
            job.error_message = 'Groq API key not configured'
            db.session.commit()
            return

        engine = AgentEngine(groq_key)
        pollinations = PollinationsAPI()

        try:
            # ── Step 1: Brand Analysis ──
            job.status = 'analyzing'
            job.current_agent = 'Brand Analyst'
            job.progress = 5
            job.message = 'Analyzing brand identity...'
            db.session.commit()

            brand_analysis = engine.analyze_brand(brand_kit)
            job.brand_analysis = json.dumps(brand_analysis)
            job.progress = 15
            db.session.commit()

            if not _check_job_control(job, db):
                return

            # ── Step 2: Content Planning ──
            job.status = 'planning'
            job.current_agent = 'Content Strategist'
            job.progress = 20
            job.message = f'Planning {job.target_count} content pieces...'
            db.session.commit()

            content_types = json.loads(job.content_types) if job.content_types else None
            content_plan = engine.plan_content(
                brand_analysis, brand_kit,
                target_count=job.target_count,
                content_types=content_types
            )
            job.content_plan = json.dumps(content_plan)
            job.progress = 30
            db.session.commit()

            if not _check_job_control(job, db):
                return

            # ── Step 3: Prompt Crafting ──
            job.status = 'crafting'
            job.current_agent = 'Prompt Crafter'
            job.progress = 35
            job.message = f'Crafting {len(content_plan)} prompts...'
            db.session.commit()

            prompts = engine.craft_prompts(content_plan, brand_analysis, brand_kit)
            job.prompts = json.dumps(prompts)
            job.progress = 40
            db.session.commit()

            if not _check_job_control(job, db):
                return

            # ── Step 4: Image Generation via Flow Bot ──
            job.status = 'generating'
            job.current_agent = 'Image Generator'
            job.message = 'Preparing Flow bot...'
            db.session.commit()

            # Create collection for this job
            collection = Collection(
                user_id=job.user_id,
                name=f"Agent — {brand_kit.name}",
                description=f"Generated by Mr.Creative Agent | {job.target_count} pieces | {brand_kit.tone} tone",
            )
            db.session.add(collection)
            db.session.commit()
            job.collection_id = collection.id
            db.session.commit()

            # Output directory
            output_dir = os.path.join(
                os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                'static', 'outputs', f'collection_{collection.id}'
            )
            os.makedirs(output_dir, exist_ok=True)

            results = []
            total = len(prompts)

            # Group prompts into batches of 4 (Flow generates up to 4 per run)
            batches = []
            for i in range(0, total, 4):
                batch = prompts[i:i+4]
                batches.append(batch)

            image_index = 0
            from modules.flow_runner import FlowSession

            session = FlowSession()
            if not session.start():
                raise RuntimeError('Could not start Flow session')

            try:
              for batch_num, batch in enumerate(batches):
                progress = 40 + int((batch_num / len(batches)) * 45)
                job.progress = progress
                job.message = f'Flow batch {batch_num+1}/{len(batches)} — generating {len(batch)} images...'
                db.session.commit()

                # Use first prompt in batch (Flow creates variations)
                prompt_item = batch[0]
                prompt_text = prompt_item.get('prompt', '') if isinstance(prompt_item, dict) else str(prompt_item)
                width = prompt_item.get('width', 1024) if isinstance(prompt_item, dict) else 1024
                height = prompt_item.get('height', 1024) if isinstance(prompt_item, dict) else 1024

                # Aspect ratio: user override or from content plan
                if hasattr(job, 'aspect_ratio') and job.aspect_ratio and job.aspect_ratio != 'mixed':
                    ar = job.aspect_ratio
                elif width > height:
                    ar = '16:9'
                elif height > width:
                    ar = '9:16'
                else:
                    ar = '1:1'

                print(f"[Pipeline] Batch {batch_num+1}: '{prompt_text[:50]}...' | {ar} | x{len(batch)}")

                try:
                    # Reference image path (only for first batch — Flow keeps it after)
                    ref_image = None
                    if job.reference_image:
                        ref_image = os.path.join(
                            os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                            'static', job.reference_image
                        )
                        if not os.path.exists(ref_image):
                            ref_image = None

                    files = session.run_batch(
                        prompt=prompt_text,
                        aspect_ratio=ar,
                        count=len(batch),
                        output_dir=output_dir,
                        reference_image=ref_image,
                        is_first=(batch_num == 0),
                    )

                    for j, filepath in enumerate(files):
                        plan_idx = image_index + j
                        plan_item = content_plan[plan_idx] if plan_idx < len(content_plan) else {}

                        rel_path = os.path.relpath(filepath,
                            os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'static')
                        ).replace('\\', '/')

                        gen = Generation(
                            user_id=job.user_id,
                            collection_id=collection.id,
                            output_path=rel_path,
                            pomelli_feature='agent',
                            status='completed',
                            tags=(plan_item.get('title', '') + ' | ' + prompt_text[:100]),
                        )
                        db.session.add(gen)
                        db.session.commit()

                        results.append({
                            'id': plan_idx + 1,
                            'filename': os.path.basename(filepath),
                            'path': rel_path,
                            'engine': 'flow',
                            'title': plan_item.get('title', f'Image {plan_idx+1}'),
                            'type': plan_item.get('type', 'unknown'),
                        })

                    print(f"[Pipeline] Batch {batch_num+1} done: {len(files)} images")

                except Exception as e:
                    print(f"[Pipeline] Batch {batch_num+1} failed: {e}")
                    import traceback
                    traceback.print_exc()
                    for j in range(len(batch)):
                        results.append({
                            'id': image_index + j + 1,
                            'error': str(e)[:100],
                            'engine': 'flow',
                        })

                image_index += len(batch)
                time.sleep(15)  # Pause between batches to avoid Flow rate-limiting

                if not _check_job_control(job, db):
                    session.close()
                    return
            finally:
                session.close()

            job.results = json.dumps(results)
            job.progress = 90
            db.session.commit()

            # ── Step 5: Post-Processing (TODO: add logo/text overlays) ──
            job.status = 'processing'
            job.current_agent = 'Post-Processor'
            job.progress = 92
            job.message = 'Applying brand elements...'
            db.session.commit()
            # Post-processing will be added later
            time.sleep(1)

            # ── Step 6: Quality Review ──
            job.status = 'reviewing'
            job.current_agent = 'Quality Reviewer'
            job.progress = 95
            job.message = 'Reviewing quality...'
            db.session.commit()

            reviewed = engine.review_results(content_plan, results, brand_analysis)
            job.results = json.dumps(reviewed)

            # ── Complete ──
            successful = len([r for r in reviewed if 'error' not in r])
            job.status = 'complete'
            job.current_agent = ''
            job.progress = 100
            job.message = f'Done! {successful}/{total} images generated'
            job.completed_at = datetime.now()
            db.session.commit()

            print(f"[Pipeline] Job {job_id} complete! {successful}/{total} images generated")

        except Exception as e:
            print(f"[Pipeline] Job {job_id} failed: {e}")
            import traceback
            traceback.print_exc()
            job.status = 'failed'
            job.error_message = str(e)[:500]
            db.session.commit()
