"""
Mr.Creative Agent Pipeline
Orchestrates all agents to generate a full content batch.
"""

import json
import os
import time
import uuid
from datetime import datetime


def run_agent_pipeline(app, job_id):
    """Run the full agent pipeline for a job. Called in a background thread."""
    with app.app_context():
        from models import db, AgentJob, BrandKit, Collection, Generation
        from modules.agents import AgentEngine
        from modules.pollinations_api import PollinationsAPI

        job = AgentJob.query.get(job_id)
        if not job:
            print(f"[Pipeline] Job {job_id} not found!")
            return

        brand_kit = BrandKit.query.get(job.brand_kit_id)
        if not brand_kit:
            job.status = 'failed'
            job.error_message = 'Brand kit not found'
            db.session.commit()
            return

        groq_key = app.config.get('GROQ_API_KEY', '')
        if not groq_key:
            job.status = 'failed'
            job.error_message = 'Groq API key not configured'
            db.session.commit()
            return

        engine = AgentEngine(groq_key)
        pollinations = PollinationsAPI()

        try:
            # ── Step 1: Brand Analysis ──
            job.status = 'analyzing'
            job.current_agent = 'Brand Analyst'
            job.progress = 5
            job.message = 'Analyzing brand identity...'
            db.session.commit()

            brand_analysis = engine.analyze_brand(brand_kit)
            job.brand_analysis = json.dumps(brand_analysis)
            job.progress = 15
            db.session.commit()

            # ── Step 2: Content Planning ──
            job.status = 'planning'
            job.current_agent = 'Content Strategist'
            job.progress = 20
            job.message = f'Planning {job.target_count} content pieces...'
            db.session.commit()

            content_types = json.loads(job.content_types) if job.content_types else None
            content_plan = engine.plan_content(
                brand_analysis, brand_kit,
                target_count=job.target_count,
                content_types=content_types
            )
            job.content_plan = json.dumps(content_plan)
            job.progress = 30
            db.session.commit()

            # ── Step 3: Prompt Crafting ──
            job.status = 'crafting'
            job.current_agent = 'Prompt Crafter'
            job.progress = 35
            job.message = f'Crafting {len(content_plan)} prompts...'
            db.session.commit()

            prompts = engine.craft_prompts(content_plan, brand_analysis, brand_kit)
            job.prompts = json.dumps(prompts)
            job.progress = 40
            db.session.commit()

            # ── Step 4: Image Generation ──
            job.status = 'generating'
            job.current_agent = 'Image Generator'
            job.message = 'Generating images...'
            db.session.commit()

            # Create collection for this job
            collection = Collection(
                user_id=job.user_id,
                name=f"Agent — {brand_kit.name}",
                description=f"Generated by Mr.Creative Agent | {job.target_count} pieces | {brand_kit.tone} tone",
            )
            db.session.add(collection)
            db.session.commit()
            job.collection_id = collection.id
            db.session.commit()

            # Output directory
            output_dir = os.path.join(
                os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                'static', 'outputs', f'collection_{collection.id}'
            )
            os.makedirs(output_dir, exist_ok=True)

            results = []
            total = len(prompts)

            for i, prompt_item in enumerate(prompts):
                prompt_text = prompt_item.get('prompt', '') if isinstance(prompt_item, dict) else str(prompt_item)
                eng = prompt_item.get('engine', 'pollinations') if isinstance(prompt_item, dict) else 'pollinations'
                w = prompt_item.get('width', 1024) if isinstance(prompt_item, dict) else 1024
                h = prompt_item.get('height', 1024) if isinstance(prompt_item, dict) else 1024

                progress = 40 + int((i / total) * 45)
                job.progress = progress
                job.message = f'Generating image {i+1}/{total} via {eng}...'
                db.session.commit()

                # For now, all go through Pollinations (Flow/Pomelli need bot automation)
                if eng in ('pollinations', 'flow', 'pomelli'):
                    filename = f"agent_{i+1:02d}_{uuid.uuid4().hex[:6]}.png"
                    save_path = os.path.join(output_dir, filename)

                    result = pollinations.generate_image(
                        prompt=prompt_text,
                        width=w,
                        height=h,
                        enhance=True,
                        save_path=save_path,
                    )

                    if result:
                        # Get content plan info for this piece
                        plan_item = content_plan[i] if i < len(content_plan) else {}

                        rel_path = f"outputs/collection_{collection.id}/{filename}"
                        gen = Generation(
                            user_id=job.user_id,
                            collection_id=collection.id,
                            output_path=rel_path,
                            pomelli_feature='agent',
                            status='completed',
                            tags=prompt_text[:200],
                        )
                        db.session.add(gen)
                        db.session.commit()

                        results.append({
                            'id': i + 1,
                            'filename': filename,
                            'path': rel_path,
                            'engine': eng,
                            'title': plan_item.get('title', f'Image {i+1}'),
                            'type': plan_item.get('type', 'unknown'),
                        })
                    else:
                        results.append({
                            'id': i + 1,
                            'error': 'Generation failed',
                            'engine': eng,
                        })

                    # Rate limit between generations
                    time.sleep(2)

            job.results = json.dumps(results)
            job.progress = 90
            db.session.commit()

            # ── Step 5: Post-Processing (TODO: add logo/text overlays) ──
            job.status = 'processing'
            job.current_agent = 'Post-Processor'
            job.progress = 92
            job.message = 'Applying brand elements...'
            db.session.commit()
            # Post-processing will be added later
            time.sleep(1)

            # ── Step 6: Quality Review ──
            job.status = 'reviewing'
            job.current_agent = 'Quality Reviewer'
            job.progress = 95
            job.message = 'Reviewing quality...'
            db.session.commit()

            reviewed = engine.review_results(content_plan, results, brand_analysis)
            job.results = json.dumps(reviewed)

            # ── Complete ──
            successful = len([r for r in reviewed if 'error' not in r])
            job.status = 'complete'
            job.current_agent = ''
            job.progress = 100
            job.message = f'Done! {successful}/{total} images generated'
            job.completed_at = datetime.now()
            db.session.commit()

            print(f"[Pipeline] Job {job_id} complete! {successful}/{total} images generated")

        except Exception as e:
            print(f"[Pipeline] Job {job_id} failed: {e}")
            import traceback
            traceback.print_exc()
            job.status = 'failed'
            job.error_message = str(e)[:500]
            db.session.commit()
